#!/bin/bash

source ./build_i386
source ./build_armv7
#source ./build_armv7s

if [ ! -d universal ]; then
     mkdir universal
fi

rm universal/*.a

LIPOPATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/

${LIPOPATH}lipo -create -arch armv7 armv7/libavcodec.a -arch i386 i386/libavcodec.a -output universal/libavcodec.a
${LIPOPATH}lipo -create -arch armv7 armv7/libavformat.a -arch i386 i386/libavformat.a -output universal/libavformat.a
${LIPOPATH}lipo -create -arch armv7 armv7/libavutil.a -arch i386 i386/libavutil.a -output universal/libavutil.a
${LIPOPATH}lipo -create -arch armv7 armv7/libswscale.a -arch i386 i386/libswscale.a -output universal/libswscale.a

#lipo -create -arch armv7 armv7/libavcodec.a -arch armv7s armv7s/libavcodec.a -arch i386 i386/libavcodec.a -output universal/libavcodec.a
#lipo -create -arch armv7 armv7/libavformat.a -arch armv7s armv7s/libavformat.a -arch i386 i386/libavformat.a -output universal/libavformat.a
#lipo -create -arch armv7 armv7/libavutil.a -arch armv7s armv7s/libavutil.a -arch i386 i386/libavutil.a -output universal/libavutil.a
#lipo -create -arch armv7 armv7/libswscale.a -arch armv7s armv7s/libswscale.a -arch i386 i386/libswscale.a -output universal/libswscale.a

