#!/bin/tcsh -f

if (! -d mini_armv7) mkdir mini_armv7

rm mini_armv7/*.a

make -f Makefile.mini clean

./configure --enable-optimizations --disable-bzlib --disable-zlib --enable-neon --disable-encoders --disable-debug --disable-doc --disable-ffprobe --disable-ffmpeg --disable-ffplay --disable-ffserver --enable-cross-compile --arch=arm --target-os=darwin --cc=/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc --as='gas-preprocessor.pl /Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc' --sysroot=/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.0.sdk --cpu=cortex-a8 --extra-cflags='-arch armv7' --extra-ldflags='-arch armv7 -isysroot /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.0.sdk' --enable-pic

cp config.mak config.mak.arm7

cp config.h config.h.arm7
cp config.h.setup config.h

make -f Makefile.mini

mv libavcodec/libavcodec.a mini_armv7/

